string_slice=input("Please enter the string in the process: ")
print(string_slice[2])
print(string_slice[1:-1])
print(string_slice[0:5])
print(string_slice[0:-2])
print(string_slice[::2])
print(string_slice[1::2])
print(string_slice[len(string_slice)::-1])
print(string_slice[-2::-2])
print("The length of string is:", len(string_slice))